// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "heroWalkFront":
            case "anim4":return [img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. f f e 2 f f f f f f 2 e f f . 
. f f f f f e e e e f f f f f . 
. . f e f b f 4 4 f b f e f . . 
. . f e 4 1 f d d f 1 4 e f . . 
. . . f e 4 d d d d 4 e f e . . 
. . f e f 2 2 2 2 e d d 4 e . . 
. . e 4 f 2 2 2 2 e d d e . . . 
. . . . f 4 4 5 5 f e e . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f . . . . . . . . . 
`, img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f e e 2 2 2 2 2 2 e f f . . 
. f f e 2 f f f f f f 2 e f f . 
. f f f f f e e e e f f f f f . 
. . f e f b f 4 4 f b f e f . . 
. . f e 4 1 f d d f 1 4 e f . . 
. . e f e 4 d d d d 4 e f . . . 
. . e 4 d d e 2 2 2 2 f e f . . 
. . . e d d e 2 2 2 2 f 4 e . . 
. . . . e e f 5 5 4 4 f . . . . 
. . . . . f f f f f f f . . . . 
. . . . . . . . . f f f . . . . 
`];
            case "heroWalkBack":
            case "anim5":return [img`
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . f f f f f 2 2 f f f f f . . 
. . f f e 2 e 2 2 e 2 e f f . . 
. . f e 2 f 2 f f 2 f 2 e f . . 
. . f f f 2 2 e e 2 2 f f f . . 
. f f e f 2 f e e f 2 f e f f . 
. f e e f f e e e e f e e e f . 
. . f e e e e e e e e e e f . . 
. . . f e e e e e e e e f . . . 
. . e 4 f f f f f f f f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . . f f f f 2 2 f f f f . . . 
. . f f e 2 e 2 2 e 2 e f f . . 
. . f e 2 f 2 f f f 2 f e f . . 
. . f f f 2 f e e 2 2 f f f . . 
. . f e 2 f f e e 2 f e e f . . 
. f f e f f e e e f e e e f f . 
. f f e e e e e e e e e e f f . 
. . . f e e e e e e e e f . . . 
. . . e f f f f f f f f 4 e . . 
. . . 4 f 2 2 2 2 2 e d d 4 . . 
. . . e f f f f f f e e 4 . . . 
. . . . f f f . . . . . . . . . 
`, img`
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . f f f f f 2 2 f f f f f . . 
. . f f e 2 e 2 2 e 2 e f f . . 
. . f e 2 f 2 f f 2 f 2 e f . . 
. . f f f 2 2 e e 2 2 f f f . . 
. f f e f 2 f e e f 2 f e f f . 
. f e e f f e e e e f e e e f . 
. . f e e e e e e e e e e f . . 
. . . f e e e e e e e e f . . . 
. . e 4 f f f f f f f f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . . f f f f 2 2 f f f f . . . 
. . f f e 2 e 2 2 e 2 e f f . . 
. . f e f 2 f f f 2 f 2 e f . . 
. . f f f 2 2 e e f 2 f f f . . 
. . f e e f 2 e e f f 2 e f . . 
. f f e e e f e e e f f e f f . 
. f f e e e e e e e e e e f f . 
. . . f e e e e e e e e f . . . 
. . e 4 f f f f f f f f e . . . 
. . 4 d d e 2 2 2 2 2 f 4 . . . 
. . . 4 e e f f f f f f e . . . 
. . . . . . . . . f f f . . . . 
`];
            case "heroWalkLeft":
            case "anim6":return [img`
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e e f f . . . . 
. . . f 2 2 2 e d d 4 . . . . . 
. . . f 2 2 2 e d d e . . . . . 
. . . f 5 5 4 f e e f . . . . . 
. . . . f f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d e e e e e f . . . 
. . . f e 4 e d d 4 f . . . . . 
. . . f 2 2 e d d e f . . . . . 
. . f f 5 5 f e e f f f . . . . 
. . f f f f f f f f f f . . . . 
. . . f f f . . . f f . . . . . 
`, img`
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e e f f . . . . 
. . . f 2 2 2 e d d 4 . . . . . 
. . . f 2 2 2 e d d e . . . . . 
. . . f 5 5 4 f e e f . . . . . 
. . . . f f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e d d 4 . . . . 
. . . f 2 2 2 2 e d d e . . . . 
. . f f 5 5 4 4 f e e f . . . . 
. . f f f f f f f f f f . . . . 
. . . f f f . . . f f . . . . . 
`];
            case "heroWalkRight":
            case "anim7":return [img`
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f 2 f . . . 
. . . f f e e e e f 2 2 2 f . . 
. . . f e e e f f e e e e f . . 
. . . f f f f e e 2 2 2 2 e f . 
. . . f e 2 2 2 f f f f e 2 f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e 4 d d d d f . . . 
. . . . f f e e 4 4 4 e f . . . 
. . . . . 4 d d e 2 2 2 f . . . 
. . . . . e d d e 2 2 2 f . . . 
. . . . . f e e f 4 5 5 f . . . 
. . . . . . f f f f f f . . . . 
. . . . . . . f f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f 2 f . . . 
. . . f f e e e e f 2 2 2 f . . 
. . . f e e e f f e e e e f . . 
. . . f f f f e e 2 2 2 2 e f . 
. . . f e 2 2 2 f f f f e 2 f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e e e d d d f . . . 
. . . . . f 4 d d e 4 e f . . . 
. . . . . f e d d e 2 2 f . . . 
. . . . f f f e e f 5 5 f f . . 
. . . . f f f f f f f f f f . . 
. . . . . f f . . . f f f . . . 
`, img`
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f 2 f . . . 
. . . f f e e e e f 2 2 2 f . . 
. . . f e e e f f e e e e f . . 
. . . f f f f e e 2 2 2 2 e f . 
. . . f e 2 2 2 f f f f e 2 f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e 4 d d d d f . . . 
. . . . f f e e 4 4 4 e f . . . 
. . . . . 4 d d e 2 2 2 f . . . 
. . . . . e d d e 2 2 2 f . . . 
. . . . . f e e f 4 5 5 f . . . 
. . . . . . f f f f f f . . . . 
. . . . . . . f f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f 2 f . . . 
. . . f f e e e e f 2 2 2 f . . 
. . . f e e e f f e e e e f . . 
. . . f f f f e e 2 2 2 2 e f . 
. . . f e 2 2 2 f f f f e 2 f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e 4 d d d d f . . . 
. . . . 4 d d e 4 4 4 e f . . . 
. . . . e d d e 2 2 2 2 f . . . 
. . . . f e e f 4 4 5 5 f f . . 
. . . . f f f f f f f f f f . . 
. . . . . f f . . . f f f . . . 
`];
            case "heroFrontAttack":
            case "anim1":return [img`
........................
.....ffff...............
...fff22fff.............
..fff2222fff............
.fffeeeeeefff...........
.ffe222222eef...........
.fe2ffffff2ef...........
.ffffeeeeffff...........
ffefbf44fbfeff..........
fee41fddf14eef..........
.ffffdddddeef...........
fddddf444eef............
fbbbbf2222f4e...........
fbbbbf2222fd4...........
.fccf45544f44...........
..ffffffff..............
....ff..ff..............
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff..........
.ffefbf44fbfeff.........
.fee41fddf14eef.........
fdfeeddddd4eff..........
fbffee444edd4e..........
fbf4f2222edde...........
fcf.f22cccee............
.ff.f44cdc4f............
....fffddcff............
.....fddcff.............
....cddc................
....cdc.................
....cc..................
........................
........................
........................
........................
`, img`
........................
........................
.......ff...............
.....ff22ff.............
...fff2222fff...........
..fff222222fff..........
..fff222222fff..........
..feeeeeeeeeeff.........
.ffe22222222eff.........
.fffffeeeefffff.........
fdfefbf44fbfeff.........
fbfe41fddf14ef..........
fbffe4dddd4efe..........
fcfef22222f4e...........
.ff4f44554f4e...........
....ffffffdde...........
.....ffffedde...........
..........ee............
.........ccc............
........cc1cc...........
.........c1c............
.........c1c............
.........c1c............
.........c1c............
`, img`
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff......ccc.
.ffefbf44fbfeff....cddc.
.ffefbf44fbfeff...cddc..
.fee4dddddd4eef.ccddc...
fdfeeddddd4eeffecddc....
fbffee4444ee4fddccc.....
fbf4f222222f1edde.......
fcf.f222222f44ee........
.ff.f445544f............
....ffffffff............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
`, img`
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff..........
.ffefbf44fbfeff.........
.fee41fddf14eef.........
..feeddddddeef..........
...fee4444eef...........
..e4f222222f4e..........
..4df222222fd4..........
..44f445544f44..........
.....ffffff.............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
........................
`];
            case "heroSideAttackLeft":
            case "anim2":return [img`
..............ffffff....
.............f2feeeeff..
............f222feeeeff.
.......cc...feeeeffeeef.
.......cdc.fe2222eeffff.
.......cddcf2effff222ef.
........cddcffeeefffffff
.........cddce44fbe44eff
..........cdceddf14d4eef
..........cccdeddd4eeef.
...........edd4e44eeff..
............ee442222f...
.............f2e2222f...
.............f554444f...
..............ffffff....
................fff.....
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
..............fff.......
.............f2fffff....
...........ff22eeeeeff..
..........ff222eeeeeeff.
..........feeeefffeeeef.
.........fe2222eeefffff.
.........f2efffff222efff
..cc.....fffeeefffffffff
..cdcc...fee44fbbe44efef
..ccddcc..feddfbb4d4eef.
....cdddceefddddd4eeef..
.....ccdcddee2222222f...
......cccdd44e544444f...
.........eeeeffffffff...
.............ff...fff...
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
...............ff.......
.............ff2ffff....
............ff2feeeeff..
...........ff22feeeeeff.
...........feeeeffeeeef.
..........fe2222eefffff.
..........f2effff222efff
..........fffeeeffffffff
..........fee44fbe44efef
...........feddfb4d4eef.
..........c.eeddd4eeef..
....ccccccceddee2222f...
.....dddddcedd44e444f...
......ccccc.eeeefffff...
..........c...ffffffff..
...............ff..fff..
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
..............ffffff....
.............f2feeeeff..
............f222feeeeff.
............feeeeffeeef.
...........fe2222eeffff.
...........f2effff222ef.
...........fffeeefffffff
...........fee44fbe44eff
............feddf14d4eef
.............fdddd4eeef.
.............fe444eddf..
.............ccc22eddf..
.............cdc22fee...
............cddc4444f...
...........cddcfffff....
..........cddc..fff.....
..........cdc...........
..........cc............
........................
........................
........................
........................
........................
........................
`, img`
..............ffffff....
.............f2feeeeff..
............f222feeeeff.
............feeeeffeeef.
...........fe2222eeffff.
...........f2effff222ef.
...........fffeeefffffff
...........fee44fbe44eff
............feddf14d4eef
.............fdddd4eeef.
.............fe444eeff..
.............f222edd4...
.............f222edde...
.............f554feef...
..............ffffff....
................fff.....
........................
........................
........................
........................
........................
........................
........................
........................
`];
            case "heroSideAttackRight":
            case "anim3":return [img`
........................
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef...cc.......
.ffffee2222ef.cdc.......
.fe222ffffe2fcddc.......
fffffffeeeffcddc........
ffe44ebf44ecddc.........
fee4d41fddecdc..........
.feee4dddedccc..........
..ffee44e4dde...........
...f222244ee............
...f2222e2f.............
...f444455f.............
....ffffff..............
.....fff................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
.......fff..............
....fffff2f.............
..ffeeeee22ff...........
.ffeeeeee222ff..........
.feeeefffeeeef..........
.fffffeee2222ef.........
fffe222fffffe2f.........
fffffffffeeefff.....cc..
fefe44ebbf44eef...ccdc..
.fee4d4bbfddef..ccddcc..
..feee4dddddfeecdddc....
...f2222222eeddcdcc.....
...f444445e44ddccc......
...ffffffffeeee.........
...fff...ff.............
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
.......ff...............
....ffff2ff.............
..ffeeeef2ff............
.ffeeeeef22ff...........
.feeeeffeeeef...........
.fffffee2222ef..........
fffe222ffffe2f..........
ffffffffeeefff..........
fefe44ebf44eef..........
.fee4d4bfddef...........
..feee4dddee.c..........
...f2222eeddeccccccc....
...f444e44ddecddddd.....
...fffffeeee.ccccc......
..ffffffff...c..........
..fff..ff...............
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef............
.ffffee2222ef...........
.fe222ffffe2f...........
fffffffeeefff...........
ffe44ebf44eef...........
fee4d41fddef............
.feee4ddddf.............
..fdde444ef.............
..fdde22ccc.............
...eef22cdc.............
...f4444cddc............
....fffffcddc...........
.....fff..cddc..........
...........cdc..........
............cc..........
........................
........................
........................
........................
........................
........................
`, img`
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef............
.ffffee2222ef...........
.fe222ffffe2f...........
fffffffeeefff...........
ffe44ebf44eef...........
fee4d41fddef............
.feee4ddddf.............
..ffee444ef.............
...4dde222f.............
...edde222f.............
...feef455f.............
....ffffff..............
.....fff................
........................
........................
........................
........................
........................
........................
........................
........................
`];
            case "heroBackAttack":
            case "anim8":return [img`
...............ffff.....
.............ffeeeeff...
............feeeffeeef..
...........fffff22fffff.
...........ffe2e22e2eff.
...........fe2f2ff2f2ef.
...........fff22ee22fff.
..........ffef2feef2feff
..........feeffeeeefeeef
...........feeeeeeeeeef.
..........fdfeeeeeeeef..
..........fe4ffffffff4e.
..........f4df222222fd4.
...........44f444444f44.
............ffffffff....
..............ff..ff....
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
...............ffffcc...
.............ffeeeeff...
............feeeffeeef..
...........fffff22fffff.
...........ffe2e22e2eff.
...........fe2f2ff2f2ef.
...........fff22ee22fff.
..........ffef2feef2feff
..........feeffeeeefeeef
...........feeeeeeeeeef.
............feeeeeeeef..
............effffffff4e.
............df222222fd4.
............ef444444f44.
..............ffffff....
..............ff..ff....
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
.............c1c........
.............c1ffff.....
.............ffeeeeff...
............feeeffeeef..
...........fffff22fffff.
...........ffe2e22e2eff.
...........fe2f2ff2f2ef.
...........fff22ee22fff.
..........ffef2feef2feff
..........feeffeeeefeeef
............feeeeeeeef..
............effffffff4e.
............df222222fd4.
............ef444444f44.
............ffffffff....
..............ff..ff....
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
...............ffff.....
.............ffeeeeff...
............feeeffeeef..
...........fffff22fffff.
...........ffe2e22e2eff.
....ccc....fe2f2ff2f2ef.
....cddc...fff22ee22fff.
.....cddc.ffef2feef2feff
......cddcfeeffeeeefeeef
.......cddcfeeeeeeeeeef.
........ccc4feeeeeeeef..
..........4d4ffffffff4e.
...........4df222222fd4.
...........44f444444f44.
..............ffffff....
..............ff..ff....
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
...............ffff.....
.............ffeeeeff...
............feeeffeeef..
...........fffff22fffff.
...........ffe2e22e2eff.
...........fe2f2ff2f2ef.
...........fff22ee22fff.
..........ffef2feef2feff
..........feeffeeeefeeef
...........feeeeeeeeeef.
............feeeeeeeef..
...........e4ffffffff4e.
...........4df222222fd4.
...........44f444444f44.
..............ffffff....
..............ff..ff....
........................
........................
........................
........................
........................
........................
........................
........................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
